name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: uubuntu-latest

    env:
      FIREBASE_API_KEY: ${{ secrets.API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_STORAGE_BUCKET }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
